name: Continous Deployment
on:
  workflow_run:
    workflows: ["Continous Integration"]
    types:
    - completed

  workflow dispatch:

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - name: Deployment to huggingface
      env:
       HF:  ${{ secrets.HF }}
      run: make deploy HF=$HF  